language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - jruby-19mode
  - rbx-2
git:
  submodules: false
gemfile:
  - Gemfile
matrix:
  include:
    - rvm: 2.1.1
      gemfile: gemfiles/rubyracer
    - rvm: 2.0.0
      gemfile: gemfiles/rubyracer
    - rvm: jruby-19mode
      gemfile: gemfiles/rubyrhino
